### ISSUE TITLE
Loading...dont shows any item

### ISSUE THREAD

**Issue by hxss** [friday/ulauncher-clipboard#38]
Hello. I just installed your extension and cant figure out how to use it. I'm on gnome(wayland), tried gpaste and clipster. Every time I type `c` in ulauncher its shows `Loading...` and nothing else and the error in terminal:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ulauncher/api/client/Client.py", line 54, in on_message
    self.extension.trigger_event(event)
  File "/usr/lib/python3.11/site-packages/ulauncher/api/client/Extension.py", line 52, in trigger_event
    action = listener.on_event(event, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hxss/.local/share/ulauncher/extensions/com.github.friday.ulauncher-clipboard/main.py", line 114, in on_event
    lines += max(1, (result.name.count('\n') + 1) * 0.85)
                     ^^^^^^^^^^^
AttributeError: 'ExtensionSmallResultItem' object has no attribute 'name'
```

**Comment by friday** [comment]
Thanks! Should be fixed, but not tested (I'm using the beta version of Ulauncher so for me it always worked). Can you update or reinstall ulauncher-clipboard and try again?

**Comment by friday** [comment]
I think that's because you're on Wayland. You need to use https://github.com/luispabon/clipman or maybe gpaste will work (but bit clipster)

I also reverted the whole last fix completely for the Ulauncher v5 version since I don't have time to test extensions for Ulauncher v5 now.

**Comment by hxss** [comment]
So I returned to xfce totally with clipman. The extension shows list of clipboard history but select action still dont update clipboard value
